# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "tar2"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.255.152"
  config.vm.synced_folder "./vagrant", "/home/vagrant"
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "512"
    v.vmx["numvcpus"] = "1"
  end
end